<?php

/**
 * Implements hook_taxonomy_term_presave().
 */

function sk_group_source_release_taxonomy_term_presave($term) {
//    dpm($term);
	
//	if($term->vocabulary_machine_name == "sk_group_name") {
//	//    We want to take the time stamp and the source, and combine those
//		// to be the term name
//		// lets get out the timestamp and convert it to text
//		if(!isset($term->sk_gsr_field_timestamp[LANGUAGE_NONE][0]['value'])) {
//			dpm("No timestamp recorded for release");
//			return;
//		}
//
//		$timestamp = $term->sk_gsr_field_timestamp[LANGUAGE_NONE][0]['value'];
//		$time_string = date("M Y", $timestamp);
//
//		// Now lets get the taxonomy term out, and get its name
//		if(!isset($term->sk_gsr_field_group_source[LANGUAGE_NONE][0]['tid'])) {
//			dpm("No group source recorded for release");
//			return;
//		}
//		$group_source_term = taxonomy_term_load($term->sk_gsr_field_group_source[LANGUAGE_NONE][0]['tid']);
//		$group_source_name = $group_source_term->name;
//
//		$term->name = $group_source_name . ' ' . $time_string;
//    }
}



/**
 * Implements hook_taxonomy_term_delete
 */
function sk_group_source_release_taxonomy_term_delete($term) {
    $group_tags_taxonomy = taxonomy_vocabulary_machine_name_load('sk_group_tag');
    if($term->vid == $group_tags_taxonomy->vid) {

        $term_id = $term->tid;
        // find all bone dysplasias that have this term
        $sql = "SELECT *
                FROM {field_data_sk_bd_tags} t
                WHERE t.sk_bd_tags_tid = $term_id";
        $results = db_query($sql);
        $bone_dysplasia_ids = array();
        foreach($results as $result) {
            $bone_dysplasia_ids[] = $result->entity_id;
        }

        // remove these tags from the bone dysplasias
        foreach($bone_dysplasia_ids as $bone_dysplasia_id) {
            $bone_dysplasia = node_load($bone_dysplasia_id);

            if(isset($bone_dysplasia->sk_bd_tags[LANGUAGE_NONE][0])) {
                foreach($bone_dysplasia->sk_bd_tags[LANGUAGE_NONE] as $sk_bd_tag) {
                    if($sk_bd_tag['value'] == $term_id) {
                        unset($sk_bd_tag);
                    }
                }
                node_save($bone_dysplasia);
            }
        }
    }
}


