<?php

/**
* Implements hook_menu().
*
*/
function skeletome_about_menu() {

    $items['about'] = array(
        'page callback' 	=> 'page_sk_about',
        'page arguments'    => array(1),
        'access arguments'  => array('access content'),
        'type'  => MENU_CALLBACK,
    );

    $items['contact'] = array(
        'page callback' 	=> 'page_sk_contact',
        'page arguments'    => array(1),
        'access arguments'  => array('access content'),
        'type'  => MENU_CALLBACK,
    );

    $items['team'] = array(
        'page callback' 	=> 'page_sk_team',
        'page arguments'    => array(1),
        'access arguments'  => array('access content'),
        'type'  => MENU_CALLBACK,
    );

    return $items;
}

function page_sk_about() {
    $output =  array(
        'skeletome_about_about_page' => array(
            '#data'     => NULL,
            '#theme'    => 'skeletome_about_about_page'
        )
    );
    return $output;
}
function page_sk_contact() {
    $output =  array(
        'skeletome_about_contact_page' => array(
            '#data'     => NULL,
            '#theme'    => 'skeletome_about_contact_page'
        )
    );
    return $output;
}
function page_sk_team() {
    $output =  array(
        'skeletome_about_team_page' => array(
            '#data'     => NULL,
            '#theme'    => 'skeletome_about_team_page'
        )
    );
    return $output;
}

/**
 * Implements hook_theme().
 */
function skeletome_about_theme($existing, $type, $theme, $path) {

    $themes['skeletome_about_about_page'] = array(
        'variables' => array(
            'data'  => NULL
        ),
        'type'      =>'theme',
        'path'      => drupal_get_path('module', 'skeletome_about') . '/templates',
        'template'  => 'about_page'
    );

    $themes['skeletome_about_contact_page'] = array(
        'variables' => array(
            'data'  => NULL
        ),
        'type'      =>'theme',
        'path'      => drupal_get_path('module', 'skeletome_about') . '/templates',
        'template'  => 'contact_page'
    );

    $themes['skeletome_about_team_page'] = array(
        'variables' => array(
            'data'  => NULL
        ),
        'type'      =>'theme',
        'path'      => drupal_get_path('module', 'skeletome_about') . '/templates',
        'template'  => 'team_page'
    );

    return $themes;
}
