<?php


require(libraries_get_path("PHP-OAuth2") . '/Client.php');
require(libraries_get_path("PHP-OAuth2") . '/GrantType/IGrantType.php');
require(libraries_get_path("PHP-OAuth2") . '/GrantType/AuthorizationCode.php');

const CLIENT_ID     = 'zlu5tonueq85';
const CLIENT_SECRET = 'QrnB1PjYgS5fiNSB';

const REDIRECT_URI           = 'http://127.0.0.1:8888/drupalv2/?q=linkedin/import';
// state is some gibberish required by linkedin (see here http://developer.linkedin.com/documents/authentication) NOT OAUTH related
const STATE                  = "DCEEFWF45453sdffef424";
// notes: can add scope to request, read here http://developer.linkedin.com/documents/authentication
const AUTHORIZATION_ENDPOINT = 'https://www.linkedin.com/uas/oauth2/authorization';
const TOKEN_ENDPOINT         = 'https://www.linkedin.com/uas/oauth2/accessToken';

/**
 * Implements hook_menu().
 *
 */
function skeletome_linkedin_menu() {

    $items['linkedin/import'] = array(
        'page callback' 	=> 'page_skeletome_linkedin_import',
        'access arguments'  => array('access content'),
        'type'  => MENU_CALLBACK
    );

    $items['linkedin/profile'] = array(
        'page callback' 	=> 'skeletome_linkedin_get_profile',
        'access arguments'  => array('access content'),
        'type'  => MENU_CALLBACK
    );

    return $items;
}

function skeletome_linkedin_get_auth_url() {
    $client = new OAuth2\Client(CLIENT_ID, CLIENT_SECRET);
    $auth_url = $client->getAuthenticationUrl(AUTHORIZATION_ENDPOINT, REDIRECT_URI);
    // Append the state to the URL (this is required by linked in)
    $auth_url .= "&state=DCEEFWF45453sdffef424";
    return $auth_url;
}

function skeletome_linkedin_get_profile() {
    $client = new OAuth2\Client(CLIENT_ID, CLIENT_SECRET);
    $response = $client->fetch('https://api.linkedin.com/v1/people/~:(first-name,last-name,summary,positions,location)', array(
        'oauth2_access_token'   => $_SESSION['linkedOAuth']['access_token'],
        'format'                => 'json'
    ));
    echo json_encode($response);
}

function page_skeletome_linkedin_import() {

    $client = new OAuth2\Client(CLIENT_ID, CLIENT_SECRET);

    $params = array('code' => $_GET['code'], 'redirect_uri' => REDIRECT_URI);
    $response = $client->getAccessToken(TOKEN_ENDPOINT, 'authorization_code', $params);


    $_SESSION['linkedOAuth'] = array(
        'just_granted'  => true,
        'access_token'  => $response['result']['access_token'],
        'expires'       => time() + $response['result']['expires_in']
    );
    $client->setAccessToken($response['result']['access_token']);

    global $user;
    drupal_goto('profile-page/' . $user->uid);
}